version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: subsapp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: subsapp_db
      MYSQL_USER: subsapp_user
      MYSQL_PASSWORD: your_db_password_here
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  johnsonflix:
    build: .
    container_name: subsapp-manager
    restart: unless-stopped
    ports:
      - "3200:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=subsapp_user
      - DB_PASSWORD=your_db_password_here
      - DB_NAME=subsapp_db
      - JWT_SECRET=johnsonflix_secret_key_2024
    depends_on:
      db:
        condition: service_healthy
    # SIMPLE: Just map everything
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mysql_data: