version: '3.8'

services:
  johnsonflix:
    build: .
    container_name: subsapp-manager
    restart: unless-stopped
    ports:
      - "3700:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=subsapp_db
      - JWT_SECRET=your_jwt_secret_change_me
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: subsapp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: subsapp_db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: